package domainmedia

import "errors"

var ErrInvalidAssetID = errors.New("media asset id must be positive")
var ErrInvalidOwnerID = errors.New("media owner id must be positive")
var ErrInvalidVideoID = errors.New("media video id must be positive")
var ErrInvalidAssetKind = errors.New("invalid media asset kind")
var ErrInvalidStorageBackend = errors.New("invalid media storage backend")
var ErrInvalidObjectKey = errors.New("invalid media object key")
var ErrInvalidContentType = errors.New("invalid media content type")
var ErrInvalidSize = errors.New("invalid media size")
var ErrInvalidChecksum = errors.New("invalid media checksum")
var ErrInvalidMediaState = errors.New("invalid media state")
var ErrInvalidVariant = errors.New("invalid media variant")
var ErrInvalidProfile = errors.New("invalid media processing profile")
var ErrInvalidUploadSession = errors.New("invalid upload session")
var ErrUploadSessionNotFound = errors.New("upload session not found")
var ErrUploadSessionExpired = errors.New("upload session expired")
var ErrUploadSessionConflict = errors.New("upload session conflict")
var ErrUploadSessionCompleted = errors.New("upload session already completed")
var ErrMediaAssetNotFound = errors.New("media asset not found")
var ErrMediaAssetPermissionDenied = errors.New("media asset permission denied")
var ErrMediaVariantNotFound = errors.New("media variant not found")
var ErrProcessingProfileNotFound = errors.New("media processing profile not found")
var ErrProcessingJobNotFound = errors.New("media processing job not found")
var ErrCleanupTaskNotFound = errors.New("media cleanup task not found")
var ErrObjectNotFound = errors.New("media object not found")
var ErrObjectChecksumMismatch = errors.New("media object checksum mismatch")
var ErrPresignUnsupported = errors.New("media object presign is unsupported")
var ErrInvalidPresignExpiry = errors.New("invalid media presign expiry")
