package domainplayback

import "errors"

// 播放领域错误用于应用层和 HTTP 层做稳定映射。
var ErrInvalidUserID = errors.New("user id must be non-negative")
var ErrInvalidVideoID = errors.New("video id must be positive")
var ErrInvalidPlatform = errors.New("platform is invalid")
var ErrInvalidNetworkType = errors.New("network type is invalid")
var ErrInvalidLimit = errors.New("limit must be positive")
var ErrInvalidFirstFrameMs = errors.New("first frame ms must be non-negative")
var ErrInvalidStutterCount = errors.New("stutter count must be non-negative")
var ErrInvalidWatchMs = errors.New("watch ms must be non-negative")
var ErrIdempotencyKeyTooLong = errors.New("idempotency key is too long")
var ErrUnsupportedTelemetryVersion = errors.New("telemetry schema version is unsupported")
var ErrInvalidTelemetryReporter = errors.New("telemetry reporter is invalid")
var ErrEmptyTelemetryBatchID = errors.New("telemetry batch id is required")
var ErrTelemetryBatchIDTooLong = errors.New("telemetry batch id is too long")
var ErrEmptyTelemetrySessionID = errors.New("telemetry playback session id is required")
var ErrTelemetrySessionIDTooLong = errors.New("telemetry playback session id is too long")
var ErrTelemetryAnonymousSessionIDTooLong = errors.New("telemetry anonymous session id is too long")
var ErrEmptyTelemetrySentAt = errors.New("telemetry sent at is required")
var ErrInvalidTelemetryContext = errors.New("telemetry context is invalid")
var ErrTelemetryStringTooLong = errors.New("telemetry string is too long")
var ErrInvalidTelemetryEventCount = errors.New("telemetry event count is invalid")
var ErrEmptyTelemetryEventID = errors.New("telemetry event id is required")
var ErrTelemetryEventIDTooLong = errors.New("telemetry event id is too long")
var ErrDuplicateTelemetryEventID = errors.New("telemetry event id is duplicated in batch")
var ErrUnsupportedTelemetryEventType = errors.New("telemetry event type is unsupported")
var ErrTelemetryEventsOutOfOrder = errors.New("telemetry events are out of order")
var ErrInvalidTelemetryOffset = errors.New("telemetry event offset is invalid")
var ErrInvalidTelemetryPosition = errors.New("telemetry media position is invalid")
var ErrInvalidTelemetryDuration = errors.New("telemetry duration is invalid")
var ErrInvalidTelemetryMetric = errors.New("telemetry metric is invalid")
var ErrInvalidTelemetryDimension = errors.New("telemetry dimension is invalid")
var ErrMissingTelemetryField = errors.New("telemetry event field is required")
var ErrUnexpectedTelemetryField = errors.New("telemetry event field is not allowed")
var ErrTelemetryBatchConflict = errors.New("telemetry batch id is already used by another payload")
var ErrTelemetryEventConflict = errors.New("telemetry event id is already used by another payload")
var ErrTelemetrySentAtOutOfRange = errors.New("telemetry sent at is outside the accepted window")
