package domaininteraction

import "errors"

// 互动领域错误覆盖点赞、收藏、评论和权限判断的业务失败原因。
var ErrInvalidUserID = errors.New("user id must be positive")
var ErrInvalidVideoID = errors.New("video id must be positive")
var ErrInvalidCommentID = errors.New("comment id must be positive")
var ErrInvalidRootCommentID = errors.New("root comment id must be positive")
var ErrInvalidReplyTargetID = errors.New("reply target comment id must be positive")
var ErrInvalidActionType = errors.New("action type is invalid")
var ErrInvalidActionEvent = errors.New("action event is invalid")
var ErrInvalidActionEventID = errors.New("action event id is invalid")
var ErrInvalidActionEventTime = errors.New("action event time is invalid")
var ErrActionEventConflict = errors.New("action event id conflicts with another payload")
var ErrActionIdempotencyConflict = errors.New("action idempotency key conflicts with another payload")
var ErrInvalidLimit = errors.New("limit must be positive")
var ErrInvalidCursor = errors.New("cursor is invalid")
var ErrInvalidCommentSort = errors.New("comment sort is invalid")
var ErrEmptyCommentContent = errors.New("comment content is required")
var ErrCommentContentTooLong = errors.New("comment content is too long")
var ErrIdempotencyKeyTooLong = errors.New("idempotency key is too long")
var ErrRecommendationRequestIDTooLong = errors.New("recommendation request id is too long")
var ErrVideoNotFound = errors.New("video not found")
var ErrCommentNotFound = errors.New("comment not found")
var ErrCommentUnavailable = errors.New("comment is unavailable")
var ErrCommentModerated = errors.New("comment is moderated")
var ErrReplyTargetUnavailable = errors.New("reply target is unavailable")
var ErrCommentPermissionDenied = errors.New("comment permission denied")
var ErrCommentIdempotencyConflict = errors.New("comment idempotency key conflicts with another payload")
var ErrCommentLikeIdempotencyConflict = errors.New("comment like idempotency key conflicts with another payload")
var ErrInvalidCommentNotification = errors.New("comment notification is invalid")
