package domainaccount

import "errors"

// 账号领域错误集中放在领域层，HTTP 层会把它们映射为对应状态码。
var ErrEmptyAccount = errors.New("account is required")
var ErrEmptyPassword = errors.New("password is required")
var ErrPasswordTooShort = errors.New("password must contain at least 8 characters")
var ErrPasswordTooLong = errors.New("password must not exceed 72 bytes")
var ErrPasswordInvalidEncoding = errors.New("password must be valid utf-8")
var ErrPasswordUnchanged = errors.New("new password must differ from current password")
var ErrCredentialChanged = errors.New("account credential changed")
var ErrEmptyNickname = errors.New("nickname is required")
var ErrInvalidUserID = errors.New("user id must be positive")
var ErrEmptyProfileUpdate = errors.New("profile update is required")
var ErrInvalidGender = errors.New("invalid gender")
var ErrEmptyProfileSettingUpdate = errors.New("profile setting update is required")
var ErrInvalidProfileVisibility = errors.New("invalid profile visibility")
var ErrUserNotFound = errors.New("user not found")
var ErrAccountAlreadyExists = errors.New("account already exists")
var ErrInvalidCredentials = errors.New("invalid credentials")
var ErrAccountFrozen = errors.New("account is frozen")
var ErrHashPasswordFailed = errors.New("hash password failed")
var ErrInvalidRefreshSession = errors.New("refresh session is invalid")
var ErrRefreshSessionExpired = errors.New("refresh session expired")
var ErrRefreshSessionRevoked = errors.New("refresh session revoked")
var ErrRefreshSessionSuperseded = errors.New("refresh session superseded")
var ErrRefreshSessionReplayed = errors.New("refresh session replayed")
var ErrInvalidRefreshSessionID = errors.New("refresh session id is invalid")
var ErrInvalidRefreshFamilyID = errors.New("refresh session family id is invalid")
var ErrInvalidRefreshSecretHash = errors.New("refresh secret hash is invalid")
var ErrInvalidAuthVersion = errors.New("authentication version is invalid")
var ErrManagedAccountNotFound = errors.New("managed ordinary account not found")
var ErrInvalidManagedAccountQuery = errors.New("managed account query is invalid")
var ErrManagedAccountQueryTooLong = errors.New("managed account query is too long")
var ErrInvalidManagedAccountStatus = errors.New("managed account status is invalid")
var ErrInvalidManagedAccountLimit = errors.New("managed account limit is invalid")
var ErrInvalidManagedAccountCursor = errors.New("managed account cursor is invalid")
var ErrInvalidAccountManagementOperation = errors.New("account management operation is invalid")
var ErrInvalidAccountManagementReason = errors.New("account management reason is invalid")
var ErrInvalidAccountManagementTransition = errors.New("account management transition is invalid")
var ErrAccountManagementVersionConflict = errors.New("account management version conflict")
var ErrAccountManagementIdempotencyKeyRequired = errors.New("account management idempotency key is required")
var ErrAccountManagementIdempotencyKeyTooLong = errors.New("account management idempotency key is too long")
var ErrAccountManagementIdempotencyConflict = errors.New("account management idempotency conflict")
var ErrInvalidAccountManagementResult = errors.New("account management result is invalid")
var ErrInvalidAccountNotification = errors.New("account lifecycle notification is invalid")
