package domainvideo

import "errors"

// 视频领域错误描述业务规则失败原因，应用层和 HTTP 层基于这些错误做转换。
var ErrInvalidVideoID = errors.New("video id must be positive")
var ErrInvalidAuthorID = errors.New("author id must be positive")
var ErrEmptyTitle = errors.New("title is required")
var ErrTitleTooLong = errors.New("title is too long")
var ErrDescriptionTooLong = errors.New("description is too long")
var ErrEmptyMediaURL = errors.New("media url is required")
var ErrEmptyCoverURL = errors.New("cover url is required")
var ErrIdempotencyKeyTooLong = errors.New("idempotency key is too long")
var ErrInvalidLimit = errors.New("limit must be positive")
var ErrInvalidOffset = errors.New("offset must be non-negative")
var ErrVideoNotFound = errors.New("video not found")
var ErrVideoPermissionDenied = errors.New("video permission denied")
var ErrDuplicateIdempotencyKey = errors.New("duplicate idempotency key")
var ErrInvalidVisibility = errors.New("invalid visibility")
var ErrVideoStateNotAllowed = errors.New("video state does not allow operation")
var ErrInvalidCursor = errors.New("invalid cursor")
var ErrInvalidDateRange = errors.New("invalid date range")
var ErrInvalidBatchAction = errors.New("invalid batch action")
var ErrTooManyVideoIDs = errors.New("too many video ids")
var ErrEmptyVideoIDs = errors.New("video ids are empty")
var ErrBatchIdempotencyConflict = errors.New("batch idempotency conflict")
var ErrCollectionNotFound = errors.New("video collection not found")
var ErrCollectionPermissionDenied = errors.New("video collection permission denied")
var ErrEmptyCollectionTitle = errors.New("collection title is empty")
var ErrCollectionTitleTooLong = errors.New("collection title is too long")
var ErrCollectionDescriptionTooLong = errors.New("collection description is too long")
var ErrIdempotencyKeyRequired = errors.New("idempotency key is required")
var ErrInvalidLocalAsset = errors.New("invalid local asset url")
var ErrLocalAssetNotFound = errors.New("local asset not found")
var ErrLocalAssetPermissionDenied = errors.New("local asset permission denied")
var ErrLocalAssetOwnershipConflict = errors.New("local asset ownership conflict")
